<a href="https://colab.research.google.com/github/Fdark18/Portifolio/blob/main/Convesoes_entre_RBG_e_CMY_e_inversamente.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Conversão de RGB para CMY**
Para converter uma cor RGB em uma cor CMY, podemos usar a seguinte fórmula:

C = 1 - R / 255
M = 1 - G / 255
Y = 1 - B / 255
Onde R, G e B são os valores da cor RGB no intervalo de 0 a 255, e C, M e Y são os valores da cor CMY no intervalo de 0 a 1.

Veja um exemplo:

Suponha que temos uma cor RGB com os valores R = 200, G = 100 e B = 50.
Para converter essa cor em CMY, aplicamos a fórmula:
C = 1 - 200 / 255 = 0.215
M = 1 - 100 / 255 = 0.608
Y = 1 - 50 / 255 = 0.804
Portanto, a cor CMY equivalente é C = 0.215, M = 0.608 e Y = 0.804.
Para fazer essa conversão em Python, podemos usar a biblioteca NumPy, que nos permite trabalhar com matrizes e vetores de forma eficiente. Veja como:

Importe o NumPy em seu código usando a declaração:

In [1]:
import numpy as np

Crie um vetor com os valores da cor RGB que você deseja converter. Por exemplo:

In [2]:
rgb = np.array([200,100,50])

Aplique a fórmula de conversão usando a operação de subtração e divisão do NumPy. Por exemplo:


In [3]:
cmy = 1 - rgb / 255
#Imprima o resultado na tela. Por exemplo:
print(cmy)

[0.21568627 0.60784314 0.80392157]


# **Conversão de CMY para RGB**
Para converter uma cor CMY em uma cor RGB, podemos usar a seguinte fórmula:

R = 255 * (1 - C)
G = 255 * (1 - M)
B = 255 * (1 - Y)
Onde C, M e Y são os valores da cor CMY no intervalo de 0 a 1, e R, G e B são os valores da cor RGB no intervalo de 0 a 255.

Veja um exemplo:

Suponha que temos uma cor CMY com os valores C = 0.215, M = 0.608 e Y = 0.804.
Para converter essa cor em RGB, aplicamos a fórmula:

Importe o NumPy em seu código usando a declaração:

In [4]:
import numpy as np

Crie um vetor com os valores da cor CMY que você deseja converter. Por exemplo:

In [5]:
cmy = np.array([0.215,0.608,0.804])

Aplique a fórmula de conversão usando a operação de multiplicação e subtração do NumPy. Por exemplo:

In [6]:
rgb = 255 * (1-cmy)
#Imprima o resultado na tela. Por exemplo:
print(rgb)

[200.175  99.96   49.98 ]
